language: generic

dist: trusty
sudo: false

before_install:
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - make setup

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - doc/preamble/twemoji

script:
  - make

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
