title: Hypersequent Classical Processes
author: Wen Kokke

# to include a new contributor, add:
# name, email, (github_username or twitter_username)
contributors:
  - name: Wen Kokke
    email: wen.kokke@ed.ac.uk
    github_username:  wenkokke
    twitter_username: wenkokke
  - name: Fabrizio Montesi
    email: fmontesi@imada.sdu.dk
    github_username:  fmontesi
  - name: Marco Peressotti
    email: peressotti@imada.sdu.dk
    github_username: mperessotti

description: "" 

baseurl: "/hcp"
url: "http://wenkokke.github.io"

markdown: kramdown
theme: minima
include:
  - pdfs/*.pdf
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - doc/
  - README.md
  - texlive.profile
