title: Hypersequent Classical Processes
author: Wen Kokke
email: wen.kokke@ed.ac.uk
twitter_username: wenkokke
github_username: wenkokke
description: "" 

baseurl: "/hcp"
url: "http://wenkokke.github.io"

markdown: kramdown
theme: minima
include:
  - pdfs/*.pdf
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - doc/
  - README.md
  - texlive.profile
